In [1]:
## Loading up all essential libraries
import numpy as np
import pandas as pd
import spacy
import nltk
import re
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')
sns.set()

C:\Users\iman_\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
nlp = spacy.load('en_core_web_lg') ## Spacy's large vocabulary library

In [3]:
df = pd.read_csv('train.csv') ## loading up the dataset

In [4]:
df['message'][6] ## checking how the typical main feature column row looks like

'RT @thenation: Mike Pence doesn’t believe in global warming or that smoking causes lung cancer. https://t.co/gvWYaauU8R'

In [5]:
df.head(20)

sentiment                                            message  tweetid
0           1  PolySciMajor EPA chief doesn't think carbon di...   625221
1           1  It's not like we lack evidence of anthropogeni...   126103
2           2  RT @RawStory: Researchers say we have three ye...   698562
3           1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736
4           1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954
5           1  Worth a read whether you do or don't believe i...   425577
6           1  RT @thenation: Mike Pence doesn’t believe in g...   294933
7           1  RT @makeandmendlife: Six big things we can ALL...   992717
8           1  @AceofSpadesHQ My 8yo nephew is inconsolable. ...   664510
9           1  RT @paigetweedy: no offense… but like… how do ...   260471
10          1  RT @StephenSchlegel: she's thinking about how ...   295793
11          1  I do hope people who are vocal about climate c...   763719
12          2  RT @tveitdal: We only have a 5 percent chance ...   454673
13          1  RT @Alifaith55: Oh. My. God.\n\nTrump's Govern...    41161
14          2  Fossil fuel giant ExxonMobil ‘misled’ the publ...   658092
15          1  RT @GlblCtzn: 'I don't wanna live forever – an...   319524
16          1  RT @jackholmes0: Issues scrubbed from https://...   698009
17          1  RT @patagonia: If our elected leaders fail to ...   490604
18          1  RT @SenSanders: We have a president-elect who ...   228658
19          0  Calum: *tweets abt reunitingish w the cast*\n-...   547924

In [325]:
b = pd.read_csv('shifter_lexicon.csv')
## a lexicon of polairty shifters

In [326]:
b

abandon  02232813  dobj
0       abandon    614907  dobj
1       abandon   2232523  dobj
2       abandon    615748  dobj
3       abandon   2080923  dobj
4         abate    245945  subj
...         ...       ...   ...
2214    wrap up    485823  dobj
2215      wreck   1568966  dobj
2216  write off   2483078  dobj
2217   yield up   2240331  dobj
2218        zap   1327970  dobj

[2219 rows x 3 columns]

## Test Model

In [5]:
df_test.head()

NameError: name 'df_test' is not defined

In [169]:
d = pd.read_csv('Lsvc_test1.csv')
d 

tweetid  sentiment
0       169760          1
1        35326          1
2       224985          1
3       476263          1
4       872928          0
...        ...        ...
10541   895714          1
10542   875167          1
10543    78329          1
10544   867455          0
10545   470892          1

[10546 rows x 2 columns]

## Pipeline

1. Run base model

### Base Model

In [6]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn import svm

## from sklearn, we are importing all the necessary libraries we will be in need off
## for modelling,  model performance and feature exrraction

In [7]:
## more models to test being imported
from xgboost import XGBClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

In [8]:
from collections import Counter ## will be used to count the number of occurrances of each Part of speech
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer ## shorten words to its root according to the word's part of speech
from nltk.corpus import wordnet ## this library will allow us to find most similar word of a particular word

normalizer = WordNetLemmatizer()
def get_part_of_speech(word):
    probable_part_of_speech = wordnet.synsets(word) ## finding word that is most similar (synonyms) for semantic reasoning
    pos_counts = Counter() # instantiating our counter class
    
    ## finding part of speech of word if part of speech is either noun, verb, adjective etc and add it up in a list
    pos_counts["n"] = len(  [ item for item in probable_part_of_speech if item.pos()=="n"]  )
    pos_counts["v"] = len(  [ item for item in probable_part_of_speech if item.pos()=="v"]  )
    pos_counts["a"] = len(  [ item for item in probable_part_of_speech if item.pos()=="a"]  )
    pos_counts["r"] = len(  [ item for item in probable_part_of_speech if item.pos()=="r"]  )
    most_likely_part_of_speech = pos_counts.most_common(1)[0][0] ## will extract the most likely part of speech from the list
    return most_likely_part_of_speech

#def preprocess_text(text):
   # cleaned = re.sub(r'\W+', '', text).lower()
   # tokenized = word_tokenize(cleaned)
   # normalized = [normalizer.lemmatize(token, get_part_of_speech(token)) for token in tokenized if len(token) > 1]
   # return normalized

In [9]:
from nltk.tokenize import TweetTokenizer ## we will use this custome TweetTokenizer from nltk to tokenize our text
import string ## from the string class, we will use its built in methods to find punctuations and numeric tokens
punctuation= list(string.punctuation)

In [10]:
## negation
negations = ['aint', 'ain\'t', 'cannot', 'cant', 'can\'t', 'darent', 'didnt', 'didn\'t', 'doesn\'t',
'doesnt', 'dont', 'don\'t', 'hadnt', 'hadn\'t','hardly', 'hasnt', 'hasn\'t', 'havent', 'haven\'t', 'havnt', 'havn\'t',
 'isnt', 'isn\'t', 'lack', 'lacking', 'lacks', 'neither', 'never', 'no', 'nobody', 'none', 'nor', 'not', 
 'nothing', 'nowhere', 'mightnt', 'mustnt' , 'neednt', 'oughtnt', 'shant', 'shouldnt', 'wasnt', 'wasn\'t', 'shouldn\'t',
 'without', 'wouldnt', 'wouldn\'t', '*n’t', 'doesn’t', 'hasn’t', 'wouldn’t', 'shouldn’t', 'wasn’t', 'can’t',
 'don’t', 'didn’t', 'ain’t', 'don\'t', 'won\'t']
def negation(df):
    b = df
    for i in negations:
        if i in df:
            b =  re.sub(i, 'not', df)
    return b
            
### some words that exist in stopwords add to the semantic meaning of a sentence. We were going to use this list of negation words
## to add more semantic and consistent meaning to our tweets by turning each negation word to not. This slightly decreased
## model performance so we will not use it

In [390]:
#df['message'] = df['message'].apply(negation) ## neglect using negation

In [392]:
df['message'][86]

'#BeforetheFlood \nEVERYONE must watch this!! people must understand global warming is very real @LeoDiCaprio \nhttps://t.co/vTqnt1f6Ni'

In [11]:
## create a fiunction that cleans up tweets
def clean(df):
    df['token'] = df['message'].apply(TweetTokenizer().tokenize) ## first we tokenize
    df['punc'] = df['token'].apply(lambda x : [i for i in x if i not in punctuation]) ## remove punctuations
    df['dig'] = df['punc'].apply(lambda x: [i for i in x if i not in list(string.digits)]) ## remove digits
    df['final'] = df['dig'].apply(lambda x: [i for i in x if len(i) > 1]) ## since we not removing stopwords, remove all words with only 1 character
    df['final'] = df['final'].apply(lambda x: [normalizer.lemmatize(token, get_part_of_speech(token)) for token in x])
    ## lemmatize by way of applying part of speech
    return df['final']

In [ ]:
df['final'] = clean(df)

In [457]:
df['final'][4] ## how our tweets look after the clean function is applied

['RT',
 '@SoyNovioDeTodas',
 "It's",
 '2016',
 'and',
 'racist',
 'sexist',
 'climate',
 'change',
 'deny',
 'bigot',
 'be',
 'lead',
 'in',
 'the',
 'poll',
 '#ElectionNight']

In [398]:
X = df['final'] ## split dataframe into features and ground truth
y = df['sentiment']

In [399]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 42)
## train test split. we find that a split size of 10% test data gives us the best performance

In [400]:
X_train = list(X_train.apply(' '.join)) ## create a single list of all tweets for both train and test features

In [401]:
X_test = list(X_test.apply(' '.join))

In [402]:
## how our test features looks like
X_train

['Why do some people still doubt global warming https://t.co/bv7K6gFrgS https://t.co/CHxym9oAoD',
 'RT @Trial_Watcher1 @DrMartyFox @SheriffClarke @LouDobbs @seanhannity the global warming scam to tax the air we breathe in order to fund',
 'RT @NatGeoChannel Watch #BeforeTheFlood right here a @LeoDiCaprio travel the world to tackle climate change https://t.co/LkDehj3tNn httÃ',
 'RT @Greenpeace What if climate change be just really big #AprilFools prank https://t.co/RKcZo4nNtf https://t.co/pUtpm0Dp4f',
 "RT @emorwee In which casually speculate that Steve Bannotn knotws climate change will cause chaos and that's sorta what he want https://t…",
 'RT @JasonLastname After war and climate change have kill u all just hope alien visit earth and ride our rollercoasters',
 "not believe Bella Thorne's and Tyler Posey's relationship exist just a much a Donald Trump doesn't believe global warming do",
 'RT @theecoheroes Fantastic Beasts Our secret weapon in combat man-made climate change animal #cli

In [361]:
#linear svc
#text_clf = Pipeline([('tfidf', TfidfVectorizer(sublinear_tf=True, smooth_idf = True, max_df = 0.3, min_df = 5, token_pattern = r'\w{1,}', strip_accents = 'ascii', ngram_range = (1, 5))), ('clf', LinearSVC(C=0.8) )])
#Logistic
#text_clf = Pipeline([('tfidf', TfidfVectorizer(sublinear_tf=True, smooth_idf = True, max_df = 0.3, min_df = 5, token_pattern = r'\w{1,}', strip_accents = 'unicode', ngram_range = (1, 5))), ('clf', LogisticRegression(C = 2, max_iter = 1000, n_jobs=-1) )])
text_clf = Pipeline([('tfidf', TfidfVectorizer(sublinear_tf=True, smooth_idf = True, max_df = 0.3, min_df = 5, token_pattern = r'\w{1,}', strip_accents = 'ascii', ngram_range = (1, 5))), ('clf', svm.SVC(gamma = 100, C = 10) )])

## The fun part

## we built a model pipeline using a tf idf vectorize to weight each word token by its level of importance and vectorize it and using a
## radial basis function SVM to train our model.
## after a bit of hyperparamater tuning, we found these paramaters to work well. An aggressive max_df removes the most common occuring words
## in the corpus. This improves our model as by looking at bag of words in our EDA, most frequent words have very little semantic meaning
## a token pattern of alphanumeric words words out best and stripping all unicode accents also improves the model
## since our average tweets are 17 words, a ngram of 1 to 5 performes best in capturing semantic meaning

## the svm paramaters were chosen because the radial function does a better job at splitting up which areas the different semantic lies
## better than a linear SVC. The reason could be that our classification is not binary.

In [403]:
text_clf.fit(X_train, y_train) ## fit and train data

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=0.3, max_features=None,
                                 min_df=5, ngram_range=(1, 5), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents='ascii',
                                 sublinear_tf=True, token_pattern='\\w{1,}',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
                     decision_function_shape='ovr', degree=3, gamma=1,
                     kernel='rbf', max_iter=

In [404]:
predictions = text_clf.predict(X_test) ## make predictions on test set

In [405]:
print(confusion_matrix(y_test, predictions)) ## confusion matrix showing where true positives and false negatives

[[ 52  17  54   3]
 [ 11  97 108   8]
 [  5  30 810  50]
 [  1   7  67 262]]


In [406]:
##after
print(classification_report(y_test, predictions)) ## here we are intrsted in the weighted f1 score

              precision    recall  f1-score   support

          -1       0.75      0.41      0.53       126
           0       0.64      0.43      0.52       224
           1       0.78      0.91      0.84       895
           2       0.81      0.78      0.79       337

    accuracy                           0.77      1582
   macro avg       0.75      0.63      0.67      1582
weighted avg       0.76      0.77      0.76      1582



In [66]:
##before
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

          -1       0.73      0.47      0.57       126
           0       0.59      0.48      0.53       224
           1       0.81      0.88      0.84       895
           2       0.77      0.80      0.79       337

    accuracy                           0.77      1582
   macro avg       0.73      0.66      0.68      1582
weighted avg       0.76      0.77      0.76      1582



###### Notes

ascii might work better as a strip accent

### Test

#### clean test data

In [439]:
df_test = pd.read_csv('test.csv') ## load unseen test set

In [440]:
#df_test['message'] = df_test['message'].apply(negation)

In [441]:
df_test['final'] = clean(df_test) ## apply same feature cleaning as with the training set

In [442]:
df_test['final'] = list(df_test['final'].apply(' '.join)) ## create a list of our test set

##### make predictions

In [443]:
df

sentiment                                            message  tweetid  \
0              1  PolySciMajor EPA chief not think carbon dioxid...   625221   
1              1  It's not like we lack evidence of anthropogeni...   126103   
2              2  RT @RawStory: Researchers say we have three ye...   698562   
3              1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736   
4              1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954   
...          ...                                                ...      ...   
15814          1  RT @ezlusztig: They took down the material on ...    22001   
15815          2  RT @washingtonpost: How climate change could b...    17856   
15816          0  notiven: RT: nytimesworld :What does Trump act...   384248   
15817         -1  RT @sara8smiles: Hey liberals the climate chan...   819732   
15818          0  RT @Chet_Cannotn: .@kurteichenwald's 'climate ...   806319   

                                                   token  \
0      [PolySciMajor, EPA, chief, not, think, carbon,...   
1      [It's, not, like, we, lack, evidence, of, anth...   
2      [RT, @RawStory, :, Researchers, say, we, have,...   
3      [#TodayinMaker, #, WIRED, :, 2016, was, a, piv...   
4      [RT, @SoyNovioDeTodas, :, It's, 2016, ,, and, ...   
...                                                  ...   
15814  [RT, @ezlusztig, :, They, took, down, the, mat...   
15815  [RT, @washingtonpost, :, How, climate, change,...   
15816  [notiven, :, RT, :, nytimesworld, :, What, doe...   
15817  [RT, @sara8smiles, :, Hey, liberals, the, clim...   
15818  [RT, @Chet_Cannotn, :, ., @kurteichenwald, ', ...   

                                                    punc  \
0      [PolySciMajor, EPA, chief, not, think, carbon,...   
1      [It's, not, like, we, lack, evidence, of, anth...   
2      [RT, @RawStory, Researchers, say, we, have, th...   
3      [#TodayinMaker, WIRED, 2016, was, a, pivotal, ...   
4      [RT, @SoyNovioDeTodas, It's, 2016, and, a, rac...   
...                                                  ...   
15814  [RT, @ezlusztig, They, took, down, the, materi...   
15815  [RT, @washingtonpost, How, climate, change, co...   
15816  [notiven, RT, nytimesworld, What, does, Trump,...   
15817  [RT, @sara8smiles, Hey, liberals, the, climate...   
15818  [RT, @Chet_Cannotn, @kurteichenwald, s, climat...   

                                                     dig  \
0      [PolySciMajor, EPA, chief, not, think, carbon,...   
1      [It's, not, like, we, lack, evidence, of, anth...   
2      [RT, @RawStory, Researchers, say, we, have, th...   
3      [#TodayinMaker, WIRED, 2016, was, a, pivotal, ...   
4      [RT, @SoyNovioDeTodas, It's, 2016, and, a, rac...   
...                                                  ...   
15814  [RT, @ezlusztig, They, took, down, the, materi...   
15815  [RT, @washingtonpost, How, climate, change, co...   
15816  [notiven, RT, nytimesworld, What, does, Trump,...   
15817  [RT, @sara8smiles, Hey, liberals, the, climate...   
15818  [RT, @Chet_Cannotn, @kurteichenwald, s, climat...   

                                                   final  
0      [PolySciMajor, EPA, chief, not, think, carbon,...  
1      [It's, not, like, we, lack, evidence, of, anth...  
2      [RT, @RawStory, Researchers, say, we, have, th...  
3      [#TodayinMaker, WIRED, 2016, be, pivotal, year...  
4      [RT, @SoyNovioDeTodas, It's, 2016, and, racist...  
...                                                  ...  
15814  [RT, @ezlusztig, They, take, down, the, materi...  
15815  [RT, @washingtonpost, How, climate, change, co...  
15816  [notiven, RT, nytimesworld, What, do, Trump, a...  
15817  [RT, @sara8smiles, Hey, liberal, the, climate,...  
15818  [RT, @Chet_Cannotn, @kurteichenwald, climate, ...  

[15819 rows x 7 columns]

In [444]:
test_predictions = text_clf.predict(df_test['final'])

In [445]:
test_predictions

array([1, 0, 1, ..., 0, 0, 1], dtype=int64)

In [446]:
df_test['sentiment'] = test_predictions

In [447]:
df_test['message'][28]

'RT @insideclimate: Gov. Jerry Brown warns Trump that California not back down on climate change https://t.co/CO0p9PU3Fd'

In [448]:
df_test.drop(['message', 'token', 'punc', 'dig', 'final'], axis = 1, inplace=True)

In [449]:
df_test.to_csv('base.csv', index=False)

In [450]:
d = pd.read_csv('base.csv')

In [453]:
d['sentiment'].value_counts()

 1    6717
 2    2357
 0    1008
-1     464
Name: sentiment, dtype: int64